version: '2.3'
services:
  app: &app
    image: amigos_invisibles
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_USER: amigos_invisibles
      RAILS_ENV: production
    env_file: ../.env.production
    volumes:
      - ../.:/usr/src/app:z
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      timeout: 5s
      retries: 10
      start_period: 10s
  proxy:
    image: nginx
    volumes:
      - ../config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../public:/usr/src/app/public:z
    depends_on:
      app:
        condition: service_healthy
    ports:
      - 3001:80
  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: amigos_invisibles_production
      POSTGRES_USER: amigos_invisibles
    env_file: ../.env.production
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app-migration:
    image: amigos_invisibles
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_USER: amigos_invisibles
      RAILS_ENV: production
    env_file: ../.env.production
    command: rails db:migrate
